// This file is auto-generated by generatePonderConfig.ts

export const chainConfigs = {
  chains: {
    arbitrum: {
      chainId: 42161,
      transport: "https://arb-mainnet.g.alchemy.com/v2/",
    },
    base: {
      chainId: 8453,
      transport: "https://base-mainnet.g.alchemy.com/v2/",
    },
    baseSepolia: {
      chainId: 84532,
      transport: "https://base-sepolia.g.alchemy.com/v2/",
    },
    optimism: {
      chainId: 10,
      transport: "https://opt-mainnet.g.alchemy.com/v2/",
    },
    optimismSepolia: {
      chainId: 11155420,
      transport: "https://opt-sepolia.g.alchemy.com/v2/",
    },
    sepolia: {
      chainId: 11155111,
      transport: "https://eth-sepolia.g.alchemy.com/v2/",
    },
  },
  cohortFactoryContracts: {
    arbitrum: {
      address: "0x738c6EE8Ce83959E2A2fF6E082d6CA5508AFe400" as `0x${string}`,
      startBlock: 340729533,
    },
    base: {
      address: "0xcd35264b9Be6EC2f837D37e1D0ae03cb594FE864" as `0x${string}`,
      startBlock: 30737573,
    },
    baseSepolia: {
      address: "0xE67cBF66A9C70afA3ebA936FC6f379dDf62df54F" as `0x${string}`,
      startBlock: 27290055,
    },
    optimism: {
      address: "0x8ca81c6aAEe9829Bc1417D1F2492E614584c3FE4" as `0x${string}`,
      startBlock: 136332861,
    },
    optimismSepolia: {
      address: "0x2890984B0f09f0d06e237B9F04E0c7Af7e86AB28" as `0x${string}`,
      startBlock: 29273527,
    },
    sepolia: {
      address: "0x630d9e93B2f3d6F41D6Af0c1D70eB21663fd1674" as `0x${string}`,
      startBlock: 7746495,
    },
  },
};
