// This file is auto-generated by generatePonderConfig.ts

export const chainConfigs = {
  chains: {
    arbitrum: {
      chainId: 42161,
      transport: "https://arb-mainnet.g.alchemy.com/v2/",
    },
    base: {
      chainId: 8453,
      transport: "https://base-mainnet.g.alchemy.com/v2/",
    },
    baseSepolia: {
      chainId: 84532,
      transport: "https://base-sepolia.g.alchemy.com/v2/",
    },
    optimism: {
      chainId: 10,
      transport: "https://opt-mainnet.g.alchemy.com/v2/",
    },
    optimismSepolia: {
      chainId: 11155420,
      transport: "https://opt-sepolia.g.alchemy.com/v2/",
    },
    sepolia: {
      chainId: 11155111,
      transport: "https://eth-sepolia.g.alchemy.com/v2/",
    },
  },
  cohortFactoryContracts: {
    arbitrum: {
      address: "0xe15f5fb3B2f21e2916C7bDD7ba0f719caD504a5d" as `0x${string}`,
      startBlock: 351421606,
    },
    base: {
      address: "0x0abc1D7F4aE715C8b1434eeFE2b38B35CED252d1" as `0x${string}`,
      startBlock: 32078609,
    },
    baseSepolia: {
      address: "0x62cc031A90B14f10aAE263ad10d3E158B271da40" as `0x${string}`,
      startBlock: 27581248,
    },
    optimism: {
      address: "0x2890984B0f09f0d06e237B9F04E0c7Af7e86AB28" as `0x${string}`,
      startBlock: 137673845,
    },
    optimismSepolia: {
      address: "0xC5006A3BE7408cFCb9Cda3903478ce184da9a88f" as `0x${string}`,
      startBlock: 29572038,
    },
    sepolia: {
      address: "0x630d9e93B2f3d6F41D6Af0c1D70eB21663fd1674" as `0x${string}`,
      startBlock: 7746495,
    },
  },
};
