// This file is auto-generated by generatePonderConfig.ts
// Updated for Ponder v1.0+ configuration format

export const chainConfigs = {
  chains: {
    arbitrum: {
      id: 42161,
      rpc: process.env.PONDER_RPC_URL_42161,
    },
    base: {
      id: 8453,
      rpc: process.env.PONDER_RPC_URL_8453,
    },
    baseSepolia: {
      id: 84532,
      rpc: process.env.PONDER_RPC_URL_84532,
    },
    localhost: {
      id: 31337,
      rpc: process.env.PONDER_RPC_URL_31337,
    },
    optimism: {
      id: 10,
      rpc: process.env.PONDER_RPC_URL_10,
    },
    optimismSepolia: {
      id: 11155420,
      rpc: process.env.PONDER_RPC_URL_11155420,
    },
    sepolia: {
      id: 11155111,
      rpc: process.env.PONDER_RPC_URL_11155111,
    },
  },
  cohortFactoryContracts: {
    arbitrum: {
      address: "0x1536a46Eae1F905005653F044Fe91dd67992e36b" as `0x${string}`,
    },
    base: {
      address: "0x738c6EE8Ce83959E2A2fF6E082d6CA5508AFe400" as `0x${string}`,
    },
    baseSepolia: {
      address: "0x495EC6dF84F3f520B54b502d93eCCde1Aa6f3f44" as `0x${string}`,
    },
    localhost: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as `0x${string}`,
    },
    optimism: {
      address: "0xF9a964E6F482d77C3F62754957706Fafc7F27d55" as `0x${string}`,
    },
    optimismSepolia: {
      address: "0xcd35264b9Be6EC2f837D37e1D0ae03cb594FE864" as `0x${string}`,
    },
    sepolia: {
      address: "0x630d9e93B2f3d6F41D6Af0c1D70eB21663fd1674" as `0x${string}`,
    },
  },
};
