import * as fs from "fs";
import * as path from "path";
import prettier from "prettier";

interface DeploymentData {
  address: string;
  receipt: {
    blockNumber: number;
  };
  abi: any[];
}

async function generatePonderConfig() {
  const deploymentsDir = "./deployments";
  const ponderPath = "../ponder";
  const ponderConfigPath = path.join(ponderPath, "src/config/chains.ts");
  const ponderAbisPath = path.join(ponderPath, "abis");

  // Ensure directories exist
  if (!fs.existsSync(path.join(ponderPath, "src/config"))) {
    fs.mkdirSync(path.join(ponderPath, "src/config"), { recursive: true });
  }
  if (!fs.existsSync(ponderAbisPath)) {
    fs.mkdirSync(ponderAbisPath, { recursive: true });
  }

  const chains: Record<string, any> = {};
  const cohortFactoryContracts: Record<string, any> = {};

  // Map chain IDs to names
  const chainIdToName: Record<string, string> = {
    "1": "mainnet",
    "137": "polygon",
    "42161": "arbitrum",
    "10": "optimism",
    "8453": "base",
    "84532": "baseSepolia",
    "11155420": "optimismSepolia",
    "534352": "scroll",
    "31337": "localhost",
    "11155111": "sepolia",
  };

  const chainRpcUrls: Record<string, string> = {
    mainnet: `https://eth-mainnet.g.alchemy.com/v2/`,
    polygon: `https://polygon-mainnet.g.alchemy.com/v2/`,
    arbitrum: `https://arb-mainnet.g.alchemy.com/v2/`,
    optimism: `https://opt-mainnet.g.alchemy.com/v2/`,
    base: `https://base-mainnet.g.alchemy.com/v2/`,
    baseSepolia: `https://base-sepolia.g.alchemy.com/v2/`,
    optimismSepolia: `https://opt-sepolia.g.alchemy.com/v2/`,
    scroll: "https://rpc.scroll.io",
    localhost: "http://localhost:8545",
    sepolia: `https://eth-sepolia.g.alchemy.com/v2/`,
  };

  if (!fs.existsSync(deploymentsDir)) {
    console.log("No deployments directory found. Run 'yarn deploy' first.");
    return;
  }

  // Read all deployments
  const chainDirs = fs
    .readdirSync(deploymentsDir)
    .filter(
      dir =>
        fs.statSync(path.join(deploymentsDir, dir)).isDirectory() &&
        fs.existsSync(path.join(deploymentsDir, dir, ".chainId")),
    );

  for (const chainDir of chainDirs) {
    const chainId = fs.readFileSync(path.join(deploymentsDir, chainDir, ".chainId"), "utf8").trim();
    const chainName = chainIdToName[chainId] || chainDir;

    // Add chain config (updated format for Ponder v1.0+)
    chains[chainName] = {
      id: Number(chainId),
      rpc: chainRpcUrls[chainName],
    };

    // Check for CohortFactory deployment
    const factoryPath = path.join(deploymentsDir, chainDir, "CohortFactory.json");
    if (fs.existsSync(factoryPath)) {
      const deployment: DeploymentData = JSON.parse(fs.readFileSync(factoryPath, "utf8"));

      cohortFactoryContracts[chainName] = {
        address: deployment.address as `0x${string}`,
        startBlock: deployment.receipt.blockNumber,
      };
    }
  }

  // Copy ABIs from artifacts
  const cohortFactoryArtifact = path.join("./artifacts/contracts/CohortFactory.sol/CohortFactory.json");
  const cohortArtifact = path.join("./artifacts/contracts/Cohort.sol/Cohort.json");

  if (fs.existsSync(cohortFactoryArtifact)) {
    const artifact = JSON.parse(fs.readFileSync(cohortFactoryArtifact, "utf8"));
    const abiContent = `// Auto-generated ABI
export const CohortFactoryAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;`;
    fs.writeFileSync(path.join(ponderAbisPath, "CohortFactory.ts"), abiContent);
  }

  if (fs.existsSync(cohortArtifact)) {
    const artifact = JSON.parse(fs.readFileSync(cohortArtifact, "utf8"));
    const abiContent = `// Auto-generated ABI
export const CohortAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;`;
    fs.writeFileSync(path.join(ponderAbisPath, "Cohort.ts"), abiContent);
  }

  // Generate config file with updated format - properly add 0x${string} type
  const configContent = `// This file is auto-generated by generatePonderConfig.ts
// Updated for Ponder v1.0+ configuration format

export const chainConfigs = {
  chains: ${JSON.stringify(chains, null, 2)},
  cohortFactoryContracts: ${JSON.stringify(cohortFactoryContracts, null, 2)
    .replace(/"address": "([^"]+)"/g, '"address": "$1" as `0x${string}`')
    .replace(/,\s*}/g, "}")},  // Clean up trailing commas
};
`;

  const formattedConfig = await prettier.format(configContent, {
    parser: "typescript",
    printWidth: 100,
    singleQuote: false,
    trailingComma: "all",
  });

  fs.writeFileSync(ponderConfigPath, formattedConfig);

  // Create tsconfig.json for ponder if it doesn't exist
  const ponderTsConfig = path.join(ponderPath, "tsconfig.json");
  if (!fs.existsSync(ponderTsConfig)) {
    const tsConfig = {
      compilerOptions: {
        target: "es2020",
        module: "esnext",
        lib: ["es2020"],
        moduleResolution: "bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        allowSyntheticDefaultImports: true,
      },
      include: ["src/**/*", "ponder.config.ts", "ponder.schema.ts", "abis/**/*"],
      exclude: ["node_modules"],
    };

    fs.writeFileSync(ponderTsConfig, JSON.stringify(tsConfig, null, 2));
    console.log(`📝 Created tsconfig.json at ${ponderTsConfig}`);
  }

  // Create .env.local template if it doesn't exist
  const envPath = path.join(ponderPath, ".env.local");
  if (!fs.existsSync(envPath)) {
    const envContent = `# Database connection (optional - uses PGlite by default)
DATABASE_URL=

# RPC URLs for each chain
PONDER_RPC_URL_1=https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY
PONDER_RPC_URL_137=https://polygon-mainnet.g.alchemy.com/v2/YOUR_KEY
PONDER_RPC_URL_42161=https://arb-mainnet.g.alchemy.com/v2/YOUR_KEY
PONDER_RPC_URL_10=https://opt-mainnet.g.alchemy.com/v2/YOUR_KEY
PONDER_RPC_URL_8453=https://base-mainnet.g.alchemy.com/v2/YOUR_KEY
PONDER_RPC_URL_84532=https://base-sepolia.g.alchemy.com/v2/YOUR_KEY
PONDER_RPC_URL_11155420=https://optimism-sepolia.g.alchemy.com/v2/YOUR_KEY
PONDER_RPC_URL_534352=https://rpc.scroll.io
PONDER_RPC_URL_31337=http://localhost:8545
PONDER_RPC_URL_11155111=https://eth-sepolia.g.alchemy.com/v2/YOUR_KEY
`;

    fs.writeFileSync(envPath, envContent);
    console.log(`📝 Created .env.local template at ${envPath}`);
  }

  console.log(`✅ Generated Ponder config at ${ponderConfigPath}`);
  console.log(`✅ Copied ABIs to ${ponderAbisPath}`);
  console.log(`✅ Setup complete! Available chains: ${Object.keys(chains).join(", ")}`);
}

// Run if called directly
if (require.main === module) {
  generatePonderConfig().catch(console.error);
}

export default generatePonderConfig;
